services:
  webp:
    container_name: propstgonz_web_nginx
    restart: always
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./html/:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro