services:
  preprocessor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/app/html
    restart: "no"
    entrypoint: ["python", "fix_links.py"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - preprocessor