services:
  preprocessor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./html:/app/html
    restart: "no"
    entrypoint: ["python", "fix_links.py"]

  nginx:
    container_name: propstgonz-web
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - preprocessor
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.propstgonz.rule=Host(`propstgonz.baronette.es`)"
      - "traefik.http.routers.propstgonz.entrypoints=websecure"
      - "traefik.http.routers.propstgonz.tls=true"
      - "traefik.http.services.propstgonz.loadbalancer.server.port=80"

networks:
  traefik-net:
    external: true